# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IWAMS
                                 A QGIS plugin
 This plugin help in planning watershed managment projects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-04
        copyright            : (C) 2019 by IIT Bombay
        email                : pratiksha1jain@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IWAMS class from file IWAMS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IWAMS import IWAMS
    return IWAMS(iface)
